### ISSUE TITLE
Droits d'écriture

### ISSUE THREAD

**Issue by JCasenave** [EcrituresNumeriques/edn6101#5]
J'ai ajouté des fichiers dans mon propre repo en local, mais impossible de pusher (erreur 403).
Peux-tu me donner les droits d'écriture ?

@emchateau

**Comment by emchateau** [comment]
Oups, je pensais que comme faisant partie de l’équipe de développeuse sur la Chaire tu y avais accès.
Je m'en occupe, désolé.

**Comment by JCasenave** [comment]
super merci !
